#pragma once

#include "gpu/core/gpu_types.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    GPU_FORMAT_UNDEFINED = 0,
    GPU_FORMAT_R8_UINT,
    GPU_FORMAT_R8_SINT,
    GPU_FORMAT_R8_UNORM,
    GPU_FORMAT_R8_SNORM,
    GPU_FORMAT_RG8_UINT,
    GPU_FORMAT_RG8_SINT,
    GPU_FORMAT_RG8_UNORM,
    GPU_FORMAT_RG8_SNORM,
    GPU_FORMAT_RGBA8_UINT,
    GPU_FORMAT_RGBA8_SINT,
    GPU_FORMAT_RGBA8_UNORM,
    GPU_FORMAT_RGBA8_UNORM_SRGB,
    GPU_FORMAT_RGBA8_SNORM,
    GPU_FORMAT_BGRA8_UNORM,
    GPU_FORMAT_BGRA8_UNORM_SRGB,
    GPU_FORMAT_R16_UINT,
    GPU_FORMAT_R16_SINT,
    GPU_FORMAT_R16_UNORM,
    GPU_FORMAT_R16_SNORM,
    GPU_FORMAT_R16_FLOAT,
    GPU_FORMAT_RG16_UINT,
    GPU_FORMAT_RG16_SINT,
    GPU_FORMAT_RG16_UNORM,
    GPU_FORMAT_RG16_SNORM,
    GPU_FORMAT_RG16_FLOAT,
    GPU_FORMAT_RGBA16_UINT,
    GPU_FORMAT_RGBA16_SINT,
    GPU_FORMAT_RGBA16_UNORM,
    GPU_FORMAT_RGBA16_SNORM,
    GPU_FORMAT_RGBA16_FLOAT,
    GPU_FORMAT_R32_UINT,
    GPU_FORMAT_R32_SINT,
    GPU_FORMAT_R32_FLOAT,
    GPU_FORMAT_RG32_UINT,
    GPU_FORMAT_RG32_SINT,
    GPU_FORMAT_RG32_FLOAT,
    GPU_FORMAT_RGB32_UINT,
    GPU_FORMAT_RGB32_SINT,
    GPU_FORMAT_RGB32_FLOAT,
    GPU_FORMAT_RGBA32_UINT,
    GPU_FORMAT_RGBA32_SINT,
    GPU_FORMAT_RGBA32_FLOAT,
    GPU_FORMAT_D32_FLOAT,
    GPU_FORMAT_D16_UNORM,
    GPU_FORMAT_D32_FLOAT_S8_UINT,
} GpuFormat;

#ifdef __cplusplus
}
#endif
